## Source: 
Feldstein, Steven (2022), “AI & Big Data Global Surveillance Index (2022 updated)”, https://data.mendeley.com/datasets/gjhf5y4xjp/4

## Data:
Information from up to 179 countries on digital repression, AI-based surveillance, and democracy index.

In [3]:
import pandas as pd
import numpy as np
import os

In [32]:
df = pd.read_excel('../data/AI Global Surveillance Index 09Mar2022.xlsx', sheet_name ='Digital Repression Inde + V-Dem')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179 entries, 0 to 178
Data columns (total 16 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Country                             179 non-null    object
 1   Region                              179 non-null    object
 2   Year                                179 non-null    int64
 3   v2x_polyarchy                       179 non-null    float64
 4   v2x_libdem                          179 non-null    float64
 5   v2x_regime                          179 non-null    object
 6   Digital Repression Index 2021       179 non-null    float64
 7   Gov SM surveillance v2smgovsmmon    179 non-null    float64
 8   Gov disinfo v2smgovdom              179 non-null    float64
 9   Pol party disinfo v2smpardom        179 non-null    float64
 10  Gov filtering v2smgovfilprc         179 non-null    float64
 11  Gov internet shutdowns v2smgovshut  179 non-null    float64
 12  Gov SM Shutdown v2smgovsm           179 non-null    float64
 13  Gov SM censorship v2smgovsmcenprc   179 non-null    float64
 14  Arrests online users (v2smarrest)   179 non-null    float64
 15  AIGS?                               97 non-null     object
dtypes: float64(11), int64(1), object(4)
memory usage: 22.5+ KB

In [33]:
def data_report(df):


    cols = pd.DataFrame(df.columns.values, columns=["COL_N"])

    types = pd.DataFrame(df.dtypes.values, columns=["DATA_TYPE"])

    percent_missing = round(df.isnull().sum() * 100 / len(df), 2)
    percent_missing_df = pd.DataFrame(percent_missing.values, columns=["MISSINGS (%)"])

    unicos = pd.DataFrame(df.nunique().values, columns=["UNIQUE_VALUES"])
    
    percent_cardin = round(unicos['UNIQUE_VALUES']*100/len(df), 2)
    percent_cardin_df = pd.DataFrame(percent_cardin.values, columns=["CARDIN (%)"])

    concatenado = pd.concat([cols, types, percent_missing_df, unicos, percent_cardin_df], axis=1, sort=False)
    concatenado.set_index('COL_N', drop=True, inplace=True)


    return concatenado.T

In [34]:
data_report(df)

COL_N,Country,Region,Year,v2x_polyarchy,v2x_libdem,v2x_regime,Digital Repression Index 2021,Gov SM surveillance v2smgovsmmon,Gov disinfo v2smgovdom,Pol party disinfo v2smpardom,Gov filtering v2smgovfilprc,Gov internet shutdowns v2smgovshut,Gov SM Shutdown v2smgovsm,Gov SM censorship v2smgovsmcenprc,Arrests online users (v2smarrest),AIGS?
DATA_TYPE,object,object,int64,float64,float64,object,float64,float64,float64,float64,float64,float64,float64,float64,float64,object
MISSINGS (%),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45.81
UNIQUE_VALUES,179,6,1,161,163,4,179,176,175,174,177,173,172,178,176,1
CARDIN (%),100.0,3.35,0.56,89.94,91.06,2.23,100.0,98.32,97.77,97.21,98.88,96.65,96.09,99.44,98.32,0.56

 - As we want to offer a global and comprehensive perspective, we are going to eliminate the column 'AIGS' (Artificial Intelligence Global Surveillance) because it only includes 82 countries out of 179.

In [35]:
df.drop(columns='AIGS?', inplace=True)

In [36]:
df.head().append(df.tail())

,Country,Region,Year,v2x_polyarchy,v2x_libdem,v2x_regime,Digital Repression Index 2021,Gov SM surveillance v2smgovsmmon,Gov disinfo v2smgovdom,Pol party disinfo v2smpardom,Gov filtering v2smgovfilprc,Gov internet shutdowns v2smgovshut,Gov SM Shutdown v2smgovsm,Gov SM censorship v2smgovsmcenprc,Arrests online users (v2smarrest)
0,Afghanistan,SCA,2021,0.160,0.021,CA,0.817572,1.054,1.564,2.702,0.941,-0.202,0.710,-0.427,2.164
1,Albania,EUR,2021,0.478,0.403,EA,-0.291090,0.151,0.310,-0.130,0.117,-0.806,-1.582,-0.912,-1.250
2,Algeria,MENA,2021,0.284,0.145,EA,1.353596,2.140,1.675,0.594,1.720,1.383,1.974,1.302,1.370
3,Angola,AFR,2021,0.351,0.190,EA,-0.251762,0.129,-0.233,0.419,-0.879,-0.374,-0.608,-0.875,-1.048
4,Argentina,WHA,2021,0.819,0.658,ED,-1.131260,-0.507,-0.925,-1.205,-2.233,-1.849,-1.827,-1.670,-2.632
174,Vietnam,EAP,2021,0.220,0.126,CA,0.891468,1.522,0.932,-0.523,2.060,-0.344,0.119,1.515,2.367
175,Yemen,MENA,2021,0.112,0.033,CA,1.509764,1.385,2.543,2.754,1.826,1.248,1.226,1.881,2.073
176,Zambia,AFR,2021,0.379,0.296,EA,0.387025,1.405,0.953,2.501,-0.098,-0.127,-0.179,-1.000,0.893
177,Zanzibar,AFR,2021,0.263,0.198,EA,0.461811,0.729,0.522,0.345,-0.628,0.006,0.194,1.269,1.346
178,Zimbabwe,AFR,2021,0.281,0.189,EA,1.022687,1.153,2.169,2.392,0.445,0.659,0.428,0.579,2.552

In [37]:
df.describe(include='all')

,Country,Region,Year,v2x_polyarchy,v2x_libdem,v2x_regime,Digital Repression Index 2021,Gov SM surveillance v2smgovsmmon,Gov disinfo v2smgovdom,Pol party disinfo v2smpardom,Gov filtering v2smgovfilprc,Gov internet shutdowns v2smgovshut,Gov SM Shutdown v2smgovsm,Gov SM censorship v2smgovsmcenprc,Arrests online users (v2smarrest)
count,179,179,179.0,179.000000,179.000000,179,1.790000e+02,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000
unique,179,6,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Afghanistan,AFR,NaN,NaN,NaN,EA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,51,NaN,NaN,NaN,60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,2021.0,0.505972,0.391978,NaN,7.960467e-10,0.106492,0.188408,0.252089,-0.258229,-0.497017,-0.526765,-0.211279,-0.073927
std,NaN,NaN,0.0,0.256652,0.260363,NaN,9.865979e-01,1.397055,1.545245,1.267526,1.553641,1.325620,1.361483,1.385306,1.604249
min,NaN,NaN,2021.0,0.016000,0.010000,NaN,-1.627828e+00,-2.885000,-2.858000,-2.993000,-2.552000,-1.915000,-1.984000,-2.211000,-2.888000
25%,NaN,NaN,2021.0,0.267000,0.147500,NaN,-8.450258e-01,-1.034000,-0.968500,-0.650000,-1.496500,-1.694000,-1.704000,-1.369500,-1.421000
50%,NaN,NaN,2021.0,0.502000,0.367000,NaN,-1.453193e-01,0.129000,0.354000,0.231000,-0.538000,-0.911000,-1.009000,-0.463000,-0.127000
75%,NaN,NaN,2021.0,0.748500,0.634500,NaN,8.354843e-01,1.140000,1.204500,1.029000,0.862500,0.330500,0.465000,0.981000,1.192000
max,NaN,NaN,2021.0,0.908000,0.878000,NaN,2.969907e+00,3.689000,3.555000,3.566000,3.869000,4.147000,4.010000,4.996000,3.091000

 -  checking duplicates:

In [38]:
df[df.duplicated(keep=False)].sum()

Country                               0.0
Region                                0.0
Year                                  0.0
v2x_polyarchy                         0.0
v2x_libdem                            0.0
v2x_regime                            0.0
Digital Repression Index 2021         0.0
Gov SM surveillance v2smgovsmmon      0.0
Gov disinfo v2smgovdom                0.0
Pol party disinfo v2smpardom          0.0
Gov filtering v2smgovfilprc           0.0
Gov internet shutdowns v2smgovshut    0.0
Gov SM Shutdown v2smgovsm             0.0
Gov SM censorship v2smgovsmcenprc     0.0
Arrests online users (v2smarrest)     0.0
dtype: float64

 - save the data for a first EDA on Digital Repression and Democracy Index:

In [13]:
path = '../data'
df.to_csv(os.path.join(path, 'DR_DI.csv'), index=False)

 - Let's see the AI Global Surveillance data:

In [4]:
df_1 = pd.read_excel('../data/AI Global Surveillance Index 09Mar2022.xlsx', sheet_name ='AIGS 2022')
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 32 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Country                                  97 non-null     object
 1   Region                                   97 non-null     object
 2   V-Dem Electoral Democracy Index 2021     97 non-null     float64
 3   V-Dem Regime Type 2021                   97 non-null     object
 4   Feldstein Digital Repression Index 2021  97 non-null     float64
 5   Freedom on the Net 2021 Status           57 non-null     object
 6   Freedom on the Net 2021 Score            57 non-null     float64
 7   Military Expenditures (USD) 2018         70 non-null     float64
 8   Military Expenditures Ranking (2018)     69 non-null     float64
 9   Member of Belt & Road Initiative         68 non-null     object
 10  China ODI Rank (EIU)                     46 non-null     float64
 11  Safe City System                         64 non-null     object
 12  Facial Recognition System                78 non-null     object
 13  Smart Policing                           69 non-null     object
 14  Social Media Surveillance                38 non-null     object
 15  China Tech                               68 non-null     float64
 16  US Tech                                  31 non-null     float64
 17  Other Countries                          49 non-null     object
 18  Company 1                                84 non-null     object
 19  Company 2                                51 non-null     object
 20  Company 3                                38 non-null     object
 21  Company 4                                21 non-null     object
 22  Company 5                                15 non-null     object
 23  Unnamed: 23                              5 non-null      object
 24  Unnamed: 24                              4 non-null      object
 25  Unnamed: 25                              2 non-null      object
 26  Unnamed: 26                              1 non-null      object
 27  Unnamed: 27                              1 non-null      object
 28  Unnamed: 28                              1 non-null      object
 29  Unnamed: 29                              1 non-null      object
 30  Unnamed: 30                              1 non-null      object
 31  Unnamed: 31                              1 non-null      object
dtypes: float64(8), object(24)
memory usage: 24.4+ KB

In [12]:
data_report(df_1.iloc[:, :15])

COL_N,Country,Region,V-Dem Electoral Democracy Index 2021,V-Dem Regime Type 2021,Feldstein Digital Repression Index 2021,Freedom on the Net 2021 Status,Freedom on the Net 2021 Score,Military Expenditures (USD) 2018,Military Expenditures Ranking (2018),Member of Belt & Road Initiative,China ODI Rank (EIU),Safe City System,Facial Recognition System,Smart Policing,Social Media Surveillance
DATA_TYPE,object,object,float64,object,float64,object,float64,float64,float64,object,float64,object,object,object,object
MISSINGS (%),0.0,0.0,0.0,0.0,0.0,41.24,41.24,27.84,28.87,29.9,52.58,34.02,19.59,28.87,60.82
UNIQUE_VALUES,97,6,89,4,97,3,42,70,69,1,45,1,1,1,1
CARDIN (%),100.0,6.19,91.75,4.12,100.0,3.09,43.3,72.16,71.13,1.03,46.39,1.03,1.03,1.03,1.03

In [13]:
data_report(df_1.iloc[:, 15:])

COL_N,China Tech,US Tech,Other Countries,Company 1,Company 2,Company 3,Company 4,Company 5,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31
DATA_TYPE,float64,float64,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object
MISSINGS (%),29.9,68.04,49.48,13.4,47.42,60.82,78.35,84.54,94.85,95.88,97.94,98.97,98.97,98.97,98.97,98.97,98.97
UNIQUE_VALUES,1,1,39,27,33,27,21,13,5,4,2,1,1,1,1,1,1
CARDIN (%),1.03,1.03,40.21,27.84,34.02,27.84,21.65,13.4,5.15,4.12,2.06,1.03,1.03,1.03,1.03,1.03,1.03

 - Remove the 'Unnamed' colums:

In [14]:
df_1.drop(list(df_1.filter(regex = 'Unnamed')), axis = 1, inplace = True)

In [17]:
df_1.iloc[:, :11].head().append(df_1.iloc[:, :11].tail())

,Country,Region,V-Dem Electoral Democracy Index 2021,V-Dem Regime Type 2021,Feldstein Digital Repression Index 2021,Freedom on the Net 2021 Status,Freedom on the Net 2021 Score,Military Expenditures (USD) 2018,Military Expenditures Ranking (2018),Member of Belt & Road Initiative,China ODI Rank (EIU)
0,Bahrain,MENA,0.122,CA,1.114753,NOT FREE,30.0,1396.808511,65.0,x,NaN
1,Burma/Myanmar,EAP,0.126,CA,2.014614,NOT FREE,17.0,2030.465547,58.0,NaN,NaN
2,China,EAP,0.078,CA,1.887927,NOT FREE,10.0,249996.900635,2.0,x,NaN
3,Hong Kong,EAP,0.267,CA,0.882240,NaN,NaN,NaN,NaN,NaN,3.0
4,Laos,EAP,0.133,CA,0.570997,NaN,NaN,NaN,NaN,x,NaN
92,Switzerland,EUR,0.885,LD,-1.436241,NaN,NaN,4795.847181,38.0,NaN,6.0
93,Taiwan,EAP,0.813,LD,-0.594070,FREE,80.0,10713.677602,23.0,NaN,13.0
94,United Kingdom,EUR,0.863,LD,-0.654357,FREE,78.0,49997.200000,7.0,NaN,40.0
95,UnitElectoral Democracy States of AmeriClosed ...,WHA,0.821,LD,-0.513142,FREE,75.0,648798.273000,1.0,NaN,2.0
96,Uruguay,WHA,0.841,LD,-1.182223,NaN,NaN,1168.130814,68.0,x,NaN

In [18]:
df_1.iloc[:, 11:].head().append(df_1.iloc[:, 11:].tail())

,Safe City System,Facial Recognition System,Smart Policing,Social Media Surveillance,China Tech,US Tech,Other Countries,Company 1,Company 2,Company 3,Company 4,Company 5
0,NaN,x,x,x,NaN,1.0,"Australia, Bahrain",iOmnicient,Pelco,LSS,NaN,NaN
1,x,x,NaN,NaN,1.0,NaN,NaN,Huawei,Hikvision,NaN,NaN,NaN
2,x,x,x,x,1.0,1.0,"Israel, UK, Sweden, Germany, Japan",Mult,Meiya Pico,Semptian,Knowlesys,Megvii
3,NaN,x,x,x,1.0,NaN,Australia,iOmnicient,Huawei,NaN,NaN,NaN
4,x,NaN,x,NaN,1.0,NaN,NaN,Huawei,NaN,NaN,NaN,NaN
92,x,x,NaN,NaN,NaN,NaN,Turkey,Ekin,NaN,NaN,NaN,NaN
93,NaN,x,NaN,NaN,NaN,NaN,"Taiwan, Japan",Lilin,Gorilla,NEC,NaN,NaN
94,x,x,x,x,1.0,1.0,Japan,Hikvision,NEC,Palantir,NaN,NaN
95,x,x,x,x,NaN,1.0,"Israel, Japan",Mult,Cognitec,Palantir,PredPol,Amazon
96,x,x,x,NaN,1.0,1.0,Spain,ZTE,Palantir,Herta,NaN,NaN

 - Some columns are binary (their values indicate belonging or not to a category); when moving from Excell to Dataframe, the empty values, indicating non-belonging, have been transformed into false Nans. Let's transform those columns:

In [20]:
# OBJECT columns with two values: 'x' and Nan
df_1[['Member of Belt & Road Initiative', 'Safe City System', 'Facial Recognition System', 'Smart Policing', 'Social Media Surveillance']].nunique()

Member of Belt & Road Initiative    1
Safe City System                    1
Facial Recognition System           1
Smart Policing                      1
Social Media Surveillance           1
dtype: int64

In [21]:
df_1[['Member of Belt & Road Initiative', 'Safe City System', 'Facial Recognition System', 'Smart Policing', 
                    'Social Media Surveillance']] = df_1[['Member of Belt & Road Initiative', 
                    'Safe City System', 'Facial Recognition System', 'Smart Policing', 'Social Media Surveillance']].replace(['x', np.nan], [1,0])

In [22]:
# OBJECT columns with names and Nan

df_1[['Other Countries','Company 1', 'Company 2', 'Company 3', 'Company 4', 'Company 5']] = df_1[['Other Countries',
'Company 1', 'Company 2', 'Company 3', 'Company 4', 'Company 5']].replace(np.nan, 0)

In [23]:
# OBJECT column 'Freedom on the Net 2021 Status'
df_1['Freedom on the Net 2021 Status'].unique()

array(['NOT FREE', nan, 'PARTLY FREE', 'FREE'], dtype=object)

In [24]:
df_1['Freedom on the Net 2021 Status'] = df_1['Freedom on the Net 2021 Status'].replace(np.nan, 'NO DATA')

In [25]:
# NUMERICAL columns: we check that there are only two values (inluding Nan)
df_1[['China Tech', 'US Tech']].nunique()

China Tech    1
US Tech       1
dtype: int64

In [26]:
df_1[['China Tech', 'US Tech']] = df_1[['China Tech', 'US Tech']].replace(np.nan, 0)
df_1[['China Tech', 'US Tech']] = df_1[['China Tech', 'US Tech']].astype(int)

In [30]:
# path = '../data'
df_1.to_csv(os.path.join(path, 'AIGS.csv'), index=False)

In [ ]:
# df_surveillance_1[['Company 1', 'Company 2', 'Company 3', 'Company 4', 'Company 5']].apply(pd.Series.value_counts)

 - fusion of both sets:

In [45]:
result = pd.concat([df, df_1], axis=1, join="inner")
result.to_csv(os.path.join(path, 'TOTAL.csv'), index=False)